---
# Define platform specific paths
web_haproxy_base:
  paths: "{{ web_haproxy_base_common['paths'] }}"
  etc: "{{ web_haproxy_base_common['etc'] }}"
  files: "{{ web_haproxy_base_common['files'] }}"
  run: "{{ web_haproxy_base_common['run'] }}"
  templates: "{{ web_haproxy_base_common['templates'] }}"
  access: "{{ web_haproxy_base_common['access'] }}"

# Define application package details
web_haproxy_profiles:
  snap: "{{ web_haproxy_profiles_common['snap'] }}"
  flatpak: "{{ web_haproxy_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      packages:
        - name: "haproxy"

# Define custom package repositories
web_haproxy_repository_custom_yum: []
web_haproxy_repository_custom_apt: []

# Set package repositories states
web_haproxy_repository_catalog_distro: {}
web_haproxy_repository_catalog_yum: {}
web_haproxy_repository_catalog_apt: {}
...
