---
- name: "Web / NGINX / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ web_nginx_application }}"
    sys_package_profiles: "{{ web_nginx_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
