---
namespace: "serdigital64"
name: "web"
version: "2.1.5"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating web tools provisioning"
license:
  - "Apache-2.0"
tags:
  - "web"
dependencies:
  serdigital64.backup: "*"
  serdigital64.system: "*"
repository: "https://github.com/aplatform64/aplatform64"
homepage: "https://github.com/aplatform64/aplatform64"
issues: "https://github.com/aplatform64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
