---
- name: "Web / MkDocs / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in web_mkdocs_platforms

- name: "Web / MkDocs / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + web_mkdocs_os_family + '.yml' }}"
  changed_when: false

- name: "Web / MkDocs / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "web_mkdocs_prerequisite.yml"
  when:
    - "'resolve_prereq' in web_mkdocs"
    - web_mkdocs['resolve_prereq']
...
