---
- name: "Web / HAProxy / Initialize"
  ansible.builtin.include_tasks:
    file: "web_haproxy_initialize.yml"

- name: "Web / HAProxy / Deploy"
  ansible.builtin.include_tasks:
    file: "web_haproxy_deploy.yml"
  when:
    - web_haproxy['deploy'] is defined
    - web_haproxy['deploy']

- name: "Web / HAProxy / Finalize"
  ansible.builtin.include_tasks:
    file: "web_haproxy_finalize.yml"
...
