---
- name: "Web / HTTPD / Initialize"
  ansible.builtin.include_tasks:
    file: "web_httpd_initialize.yml"

- name: "Web / HTTPD / Deploy"
  ansible.builtin.include_tasks:
    file: "web_httpd_deploy.yml"
  when:
    - web_httpd['deploy'] is defined
    - web_httpd['deploy']

- name: "Web / HTTPD / Finalize"
  ansible.builtin.include_tasks:
    file: "web_httpd_finalize.yml"
...
