---
- name: "Web / HTTPD / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ web_httpd_application | default('web_httpd_application') }})"
    quiet: true
    that:
      - web_httpd_application is defined
      - web_httpd_application | length > 0
      - web_httpd_application['name'] is defined
      - web_httpd_application['type'] is defined
      - web_httpd_application['version'] is defined
      - web_httpd_application['installed'] is defined

- name: "Web / HTTPD / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "web_httpd_deploy_package.yml"
  when:
    - web_httpd_application is defined
...
