---
- name: "Web / MkDocs / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: install application"
      vars:
        web_mkdocs:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.web.web_mkdocs"
...
